### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by atty31** [mkubenka/ansible-role-geoip#1]
Hi,

When I run the role, i am getting this warning:

`[DEPRECATION WARNING]: Invoking "yum" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `pkg: "{{ item }}"`, please use `pkg: ['GeoIP']` and remove the loop. This feature will be removed in
version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

Can you please fix it ? Thnx

**Comment by mkubenka** [comment]
Fixed in 2afdfa6be520b295de6fc4540074ef4d7120e9bb
